export const ReferralABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AlreadyInitialize", type: "error" },
  { inputs: [], name: "InsufficientRewardToken", type: "error" },
  { inputs: [], name: "InvalidAddress", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "startIndex", type: "uint256" },
      { internalType: "uint256", name: "endIndex", type: "uint256" },
    ],
    name: "InvalidRange",
    type: "error",
  },
  { inputs: [], name: "InvalidReferrer", type: "error" },
  { inputs: [], name: "NotInitialize", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReferralAlreadyExists", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "handler", type: "address" }],
    name: "UnauthorizedHandler",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "rewardToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalAllocation",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "initialHandler",
        type: "address",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    name: "LevelReward",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "rank",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RankAchieved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "rank",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reward",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "goldValue",
        type: "uint256",
      },
    ],
    name: "RankRewardInfo",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
    ],
    name: "ReferralAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "bonusAmount",
        type: "uint256",
      },
    ],
    name: "ReferralBonus",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    name: "ReferralReward",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "user_", type: "address" },
      { internalType: "address", name: "referrer_", type: "address" },
    ],
    name: "addReferral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "account_", type: "address" },
      { internalType: "uint256", name: "actualToken_", type: "uint256" },
      { internalType: "uint256", name: "usdAmount_", type: "uint256" },
    ],
    name: "distributeRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getAchievedRanks",
    outputs: [
      { internalType: "uint256[]", name: "ranks", type: "uint256[]" },
      { internalType: "string[]", name: "rewards", type: "string[]" },
      { internalType: "uint256[]", name: "goldValues", type: "uint256[]" },
      { internalType: "uint256[]", name: "achievedAts", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "referrer_", type: "address" }],
    name: "getActiveDirectReferrals",
    outputs: [
      { internalType: "address[]", name: "activeUsers", type: "address[]" },
      { internalType: "uint256", name: "activeCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getCompleteUserData",
    outputs: [
      { internalType: "address", name: "referrer", type: "address" },
      {
        internalType: "uint256",
        name: "directReferralsCount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalReferralRewards",
        type: "uint256",
      },
      { internalType: "uint256", name: "selfVolumeTokens", type: "uint256" },
      { internalType: "uint256", name: "selfVolumeUsd", type: "uint256" },
      { internalType: "uint256", name: "teamVolumeTokens", type: "uint256" },
      { internalType: "uint256", name: "teamVolumeUsd", type: "uint256" },
      { internalType: "uint256", name: "currentRank", type: "uint256" },
      { internalType: "uint256", name: "firstPurchaseTime", type: "uint256" },
      { internalType: "uint256", name: "lastPurchaseTime", type: "uint256" },
      { internalType: "uint256", name: "totalPurchases", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getCurrentRankReward",
    outputs: [
      { internalType: "uint256", name: "rank", type: "uint256" },
      { internalType: "string", name: "reward", type: "string" },
      { internalType: "uint256", name: "goldValue", type: "uint256" },
      { internalType: "uint256", name: "achievedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "referrer_", type: "address" },
      { internalType: "uint256", name: "startIndex_", type: "uint256" },
      { internalType: "uint256", name: "endIndex_", type: "uint256" },
    ],
    name: "getDirectReferrals",
    outputs: [{ internalType: "address[]", name: "users", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "referrer_", type: "address" },
      { internalType: "uint256", name: "startIndex_", type: "uint256" },
      { internalType: "uint256", name: "endIndex_", type: "uint256" },
    ],
    name: "getDirectReferralsPurchaseInfo",
    outputs: [
      { internalType: "address[]", name: "users", type: "address[]" },
      {
        internalType: "uint256[]",
        name: "firstPurchaseTime",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "lastPurchaseTime",
        type: "uint256[]",
      },
      { internalType: "uint256[]", name: "totalPurchases", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "level", type: "uint256" }],
    name: "getLevelConfig",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "percentage", type: "uint256" },
          { internalType: "uint256", name: "minDirects", type: "uint256" },
          { internalType: "uint256", name: "minTeamVolume", type: "uint256" },
        ],
        internalType: "struct NABReferral.LevelConfig",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getLevelWiseCounts",
    outputs: [
      { internalType: "uint256[10]", name: "levelCounts", type: "uint256[10]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getRank",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "rank", type: "uint256" }],
    name: "getRankConfig",
    outputs: [
      { internalType: "uint256", name: "selfBusinessUsd", type: "uint256" },
      { internalType: "uint256", name: "teamBusinessUsd", type: "uint256" },
      { internalType: "uint256", name: "goldValue", type: "uint256" },
      { internalType: "string", name: "reward", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user_", type: "address" },
      { internalType: "uint256", name: "rank_", type: "uint256" },
    ],
    name: "getRankRewardInfo",
    outputs: [
      { internalType: "string", name: "reward", type: "string" },
      { internalType: "uint256", name: "goldValue", type: "uint256" },
      { internalType: "uint256", name: "achievedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "referrer_", type: "address" }],
    name: "getReferralRewards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "referrer_", type: "address" }],
    name: "getReferralsCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getReferrer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getSelfBusinessUsd",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getSelfVolume",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "referrer_", type: "address" }],
    name: "getTeamBusinessUsd",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "referrer_", type: "address" }],
    name: "getTeamVolume",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user_", type: "address" }],
    name: "getUserPurchaseInfo",
    outputs: [
      { internalType: "uint256", name: "firstPurchaseTime", type: "uint256" },
      { internalType: "uint256", name: "lastPurchaseTime", type: "uint256" },
      { internalType: "uint256", name: "totalPurchases", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "rewardToken_", type: "address" },
      {
        internalType: "uint256",
        name: "totalReferralBonusAllocation_",
        type: "uint256",
      },
      { internalType: "address", name: "initialHandler_", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isInitialized",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "levelConfigs",
    outputs: [
      { internalType: "uint256", name: "percentage", type: "uint256" },
      { internalType: "uint256", name: "minDirects", type: "uint256" },
      { internalType: "uint256", name: "minTeamVolume", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nabRewardToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "rankConfigs",
    outputs: [
      { internalType: "uint256", name: "selfBusinessUsd", type: "uint256" },
      { internalType: "uint256", name: "teamBusinessUsd", type: "uint256" },
      { internalType: "uint256", name: "goldValue", type: "uint256" },
      { internalType: "string", name: "reward", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalReferralBonusAllocation",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalReferralBonusReward",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "account_", type: "address" },
      { internalType: "uint256", name: "amount_", type: "uint256" },
    ],
    name: "transferRewardToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "handler_", type: "address" },
      { internalType: "bool", name: "isEnable_", type: "bool" },
    ],
    name: "updateHandler",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "level", type: "uint256" },
      { internalType: "uint256", name: "percentage", type: "uint256" },
      { internalType: "uint256", name: "minDirects", type: "uint256" },
      { internalType: "uint256", name: "minTeamVolumeUsd", type: "uint256" },
    ],
    name: "updateLevelConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
